application: t-decoder-840
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: blog_cached.application

libraries:
- name: jinja2
  version: latest
